"""Generic OO-LD → Wunderbaum tree builder.

Given a set of Python objects and a list of RelationSpecs, builds a
Wunderbaum-compatible source list automatically.

Key concepts
------------
ObjectSource     — where objects come from (in-memory or lazy/remote).
RelationSpec     — a named rule: for each object, produce (child→parent) edges.
OOLDTreeBuilder  — assembles nodes+edges, walks MRO for SubClassOf, then
                   delegates to build_oold_tree_source.

Edge direction convention (same as panelini dag_projection.py):
  "from" = child / more specific   e.g. CylindricalCell, cell_a, test_run
  "to"   = parent / more general   e.g. BatteryCell, CylindricalCell, cell_a

SubClassOf edges are added automatically by walking the Python MRO of every
class node encountered, up to (and including) `ceiling`, which becomes the
tree root.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Callable, Dict, List, Optional, Protocol, Set, Tuple

from panelini.panels.wunderbaum import Wunderbaum

from opensemantic.batteries.view._battery_utils import build_oold_tree_source


# ---------------------------------------------------------------------------
# RelationSpec and factory helpers
# ---------------------------------------------------------------------------

@dataclass
class RelationSpec:
    """One edge-extraction rule.

    ``extract(obj)`` returns a list of *parent* objects or classes for ``obj``.
    The builder adds edges  from=node_id(obj)  to=node_id(target).
    """
    relation: str
    extract: Callable[[Any], List[Any]]


def has_type() -> RelationSpec:
    """Edge: instance → its direct Python class  (relation = "HasType")."""
    return RelationSpec("HasType", lambda obj: [type(obj)])


def field_rel(field: str, relation: str) -> RelationSpec:
    """Edge: obj → getattr(obj, field)  (handles None, single value, list).

    Example::

        field_rel("device_under_test", "HasDUT")
        field_rel("protocol", "HasProtocol")
    """
    def _extract(obj: Any) -> List[Any]:
        val = getattr(obj, field, None)
        if val is None:
            return []
        return list(val) if isinstance(val, (list, tuple)) else [val]

    return RelationSpec(relation, _extract)


# ---------------------------------------------------------------------------
# ObjectSource — where objects come from
# ---------------------------------------------------------------------------

class ObjectSource(Protocol):
    def get_objects(self) -> List[Any]: ...


class PythonSource:
    """Objects already in memory."""

    def __init__(self, objects: List[Any]) -> None:
        self._objects = list(objects)

    def get_objects(self) -> List[Any]:
        return self._objects


class LazySource:
    """Objects loaded on demand via a callable.

    Suitable for any backend — OSW, SPARQL, document store, etc.::

        def load_cells():
            return osw.load_instances("opensemantic:BatteryCell")

        source = LazySource(load_cells)
    """

    def __init__(self, loader: Callable[[], List[Any]]) -> None:
        self._loader = loader
        self._cache: Optional[List[Any]] = None

    def get_objects(self) -> List[Any]:
        if self._cache is None:
            self._cache = self._loader()
        return self._cache


# ---------------------------------------------------------------------------
# Node identity helpers
# ---------------------------------------------------------------------------

def _node_id(obj: Any) -> str:
    """Stable node ID for an object.

    Priority:
      1. ``str(obj.uuid)``   — auto-generated by OswBaseModel for all Item subclasses
      2. label text          — fallback for objects without uuid
      3. ``id(obj)``         — last resort (session-stable, not cross-run-stable)
    """
    if isinstance(obj, type):
        return obj.__name__
    uuid = getattr(obj, "uuid", None)
    if uuid is not None:
        return str(uuid)
    labels = getattr(obj, "label", None)
    if labels:
        text = getattr(labels[0], "text", None)
        if text:
            return text
    return str(id(obj))


def _default_label(obj: Any) -> str:
    if isinstance(obj, type):
        return obj.__name__
    labels = getattr(obj, "label", None)
    if labels:
        return getattr(labels[0], "text", str(labels[0]))
    return type(obj).__name__


# ---------------------------------------------------------------------------
# OOLDTreeBuilder
# ---------------------------------------------------------------------------

class OOLDTreeBuilder:
    """Builds a Wunderbaum tree from Python objects and RelationSpecs.

    Parameters
    ----------
    source
        Where instances come from (PythonSource, LazySource, or any ObjectSource).
    relations
        List of RelationSpecs that define how edges are extracted.
        All discovered instances are also run through every spec
        (breadth-first), so e.g. cells discovered via ``field_rel(
        "device_under_test", "HasDUT")`` will also be passed through
        ``has_type()`` automatically.
    ceiling
        Walk the Python MRO up to (and including) this class.
        This class becomes the tree root.  ``None`` means walk until
        ``object`` (use with care — produces very deep trees).
    label_fn
        How to produce the display label for a node.  Defaults to
        ``obj.label[0].text`` for instances, ``cls.__name__`` for classes.
    """

    def __init__(
        self,
        source: ObjectSource,
        relations: List[RelationSpec],
        ceiling: Optional[type] = None,
        label_fn: Callable[[Any], str] = _default_label,
    ) -> None:
        self._source = source
        self._relations = relations
        self._ceiling = ceiling
        self._label_fn = label_fn

        self._nodes: Dict[str, Dict] = {}
        self._edges: List[Dict] = []
        self._edge_set: Set[Tuple[str, str, str]] = set()
        self._object_map: Dict[str, Any] = {}
        self._class_registry: Dict[str, type] = {}
        self._built = False

    # -- Internal build -------------------------------------------------------

    def _add_edge(self, from_id: str, to_id: str, relation: str) -> None:
        key = (from_id, to_id, relation)
        if key not in self._edge_set:
            self._edge_set.add(key)
            self._edges.append({"from": from_id, "to": to_id, "relation": relation})

    def _ensure_class_node(self, cls: type) -> None:
        """Add a class node and walk MRO up to ceiling (SubClassOf edges)."""
        node_id = cls.__name__
        if node_id in self._class_registry:
            return

        self._nodes[node_id] = {"label": cls.__name__, "kind": "class"}
        self._class_registry[node_id] = cls

        # Ceiling is the root — stop here, don't walk further up.
        if self._ceiling is not None and cls is self._ceiling:
            return

        for parent in cls.__bases__:
            if parent is object:
                continue
            # Only follow parents that are at or below ceiling.
            if self._ceiling is not None:
                try:
                    if not issubclass(parent, self._ceiling):
                        continue
                except TypeError:
                    continue
            self._add_edge(node_id, parent.__name__, "SubClassOf")
            self._ensure_class_node(parent)

    def _build(self) -> None:
        if self._built:
            return

        queue: List[Any] = list(self._source.get_objects())
        processed: Set[str] = set()

        while queue:
            obj = queue.pop(0)
            if isinstance(obj, type):
                self._ensure_class_node(obj)
                continue

            obj_id = _node_id(obj)
            if obj_id in processed:
                continue
            processed.add(obj_id)

            if obj_id not in self._nodes:
                self._nodes[obj_id] = {
                    "label": self._label_fn(obj),
                    "kind": "instance",
                }
                self._object_map[obj_id] = obj

            for spec in self._relations:
                for target in spec.extract(obj):
                    if isinstance(target, type):
                        target_id = target.__name__
                        self._ensure_class_node(target)
                    else:
                        target_id = _node_id(target)
                        if target_id not in self._nodes:
                            self._nodes[target_id] = {
                                "label": self._label_fn(target),
                                "kind": "instance",
                            }
                            self._object_map[target_id] = target
                        if target_id not in processed:
                            queue.append(target)

                    self._add_edge(obj_id, target_id, spec.relation)

        self._built = True

    # -- Public API -----------------------------------------------------------

    def build_nodes(self) -> Dict[str, Dict]:
        """Return the ``{node_id: {label, kind}}`` dict after building."""
        self._build()
        return dict(self._nodes)

    def build_edges(self) -> List[Dict]:
        """Return the ``[{from, to, relation}]`` list after building."""
        self._build()
        return list(self._edges)

    def build_source(self) -> List[Dict]:
        """Return a Wunderbaum-ready source list."""
        self._build()
        return build_oold_tree_source(self._nodes, self._edges)

    def get_object_map(self) -> Dict[str, Any]:
        """Return ``{node_id: Python object}`` for all instance nodes.

        Use this instead of maintaining a manual ``cell_objects`` dict.
        Compatible with ``get_checked_instance_ids`` from ``_battery_utils``.
        """
        self._build()
        return dict(self._object_map)

    def widget(
        self,
        columns: Optional[List[Dict]] = None,
        options: Optional[Dict] = None,
        **kwargs: Any,
    ) -> Wunderbaum:
        """Build and return a Wunderbaum widget.

        Sensible defaults are applied if ``columns`` or ``options`` are omitted.
        """
        source = self.build_source()
        cols = columns or [{"id": "*", "title": "Node", "width": "220px"}]
        opts = options or {"checkbox": True, "selectMode": "hier"}
        return Wunderbaum(source=source, columns=cols, options=opts, **kwargs)
