# This file is generated by the osw-python-package-generator
# (https://github.com/OpenSemanticWorld-Packages/osw-python-package-generator)
# from the world.opensemantic.batteries schema package. Do not edit manually.
#
# Placeholder: Pydantic v2 battery models have not been generated yet. Run the
# generator (see tools/osw-python-package-generator) to populate this module.
